name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

categories:
  - title: 'Enhancements'
    label: 'Enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'Fix'
      - 'Bugfix'
      - 'Bug'
  - title: 'Refactor'
    label: 'Refactor'
  - title: 'Dependencies'
    labels:
      - 'Dependencies'
  - title: 'Pipeline'
    labels:
      - 'Pipeline'
      - 'CI'
      - 'Build'

version-resolver:
  major:
    labels:
      - 'BreakingChange'
  minor:
    labels:
      - 'Feature'
      - 'Enhancement'
  patch:
    labels:
      - 'Bug'
      - 'BugFix'
      - 'Dependencies'
  default: patch
